use_frameworks!

target 'UserDefaultsPlusPlus_Example' do
  pod 'UserDefaultsPlusPlus', :path => '../'

  target 'UserDefaultsPlusPlus_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
